apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-tal.fullname" . }}-public
  labels:
    {{- include "devops-tal.labels" . | nindent 4 }}-public
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "devops-tal.selectorLabels" . | nindent 4 }}-public
